[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "presidio_analyzer"
description = "Presidio Analyzer package"
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.8"
keywords = ["presidio_analyzer"]
urls = {Homepage = "https://github.com/Microsoft/presidio"}
dependencies = [
    "spacy>=3.4.4, <4.0.0",
    "regex",
    "tldextract",
    "pyyaml",
    "phonenumbers>=8.12,<9.0.0",
]
dynamic = ["version"]
readme = "README.md"

[project.optional-dependencies]
server = ["flask>=1.1"]
transformers = ["spacy_huggingface_pipelines"]
stanza = [
    "stanza",
    "spacy_stanza",
]
azure-ai-language = [
    "azure-ai-textanalytics",
    "azure-core",
]
all = ['presidio_analyzer[server,transformers,stanza,azure-ai-language]']


[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["conf/*",]

[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[tool.pdm.dev-dependencies]
lint = ["ruff"]
test = ["pytest", "pytest-mock", "python-dotenv"]
