[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "presidio_structured"
description = "Presidio structured package - analyzes and anonymizes structured and semi-structured data."
license = {text = "MIT License"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
keywords = ["presidio_structured"]
urls = {Homepage = "https://github.com/microsoft/presidio"}
requires-python = ">=3.8"
dependencies = [
    "presidio-analyzer>=2.2",
    "presidio-anonymizer>=2.2",
]
dynamic = ["version"]


[tool.pdm.dev-dependencies]
dev = ["pip", "ruff", "pytest", "pytest-mock", "python-dotenv", "pre_commit"]

[tool.pdm.version]
source = "file"
path = "presidio_cli.__init__.py"
