[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "presidio_anonymizer"
description = "Presidio Anonymizer package - replaces analyzed text with desired values."
license = {text = "MIT License"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.8"
keywords = ["presidio_anonymizer"]
urls = {Homepage = "https://github.com/Microsoft/presidio"}
dependencies = ["pycryptodome>=3.10.1"]
dynamic = ["version"]
readme = "README.md"

[project.optional-dependencies]
server = ["flask>=1.1"]

[tool.pdm.dev-dependencies]
dev = ["pip", "ruff", "pytest", "pytest-mock", "python-dotenv", "pre_commit"]

[tool.pdm.version]
source = "file"
path = "VERSION"
